spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/gymdb
    username: postgres
    password: "@Designer1980"
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.epam.gym: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    com.epam.gym.client: DEBUG